name: balrain
description: BALRAIN â€” Rational Insight App
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.5.1
  fl_chart: ^0.68.0
  intl: ^0.19.0
  http: ^1.2.2
  web_socket_channel: ^2.4.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
